# Generated by Django 4.1.6 on 2023-02-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitAccounts',
            new_name='Item',
        ),
    ]
